=== dukai2016/test/testproject/target/test-classes/treatmentSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#", 
  "definitions": {}, 
  "id": "http://example.com/example.json", 
  "properties": {
    "actualEndDate": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/actualEndDate", 
      "title": "The actualenddate schema.", 
      "type": "null"
    }, 
    "catalogueItemId": {
      "default": 112, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "112"
      ], 
      "id": "/properties/catalogueItemId", 
      "title": "The catalogueitemid schema.", 
      "type": "integer"
    }, 
    "catalogueItemIdL2": {
      "default": 45, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "45"
      ], 
      "id": "/properties/catalogueItemIdL2", 
      "title": "The catalogueitemidl2 schema.", 
      "type": "integer"
    }, 
    "courseCompletedCodeCncptId": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/courseCompletedCodeCncptId", 
      "title": "The coursecompletedcodecncptid schema.", 
      "type": "null"
    }, 
    "createdBy": {
      "default": "ESTI_DEMO", 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "ESTI_DEMO"
      ], 
      "id": "/properties/createdBy", 
      "title": "The createdby schema.", 
      "type": "string"
    }, 
    "createdOn": {
      "default": "08/21/2017", 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "08/21/2017"
      ], 
      "id": "/properties/createdOn", 
      "title": "The createdon schema.", 
      "type": "string"
    }, 
    "discontinuedBy": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/discontinuedBy", 
      "title": "The discontinuedby schema.", 
      "type": "null"
    }, 
    "discontinuedByProviderOther": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/discontinuedByProviderOther", 
      "title": "The discontinuedbyproviderother schema.", 
      "type": "null"
    }, 
    "discontinuedDate": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/discontinuedDate", 
      "title": "The discontinueddate schema.", 
      "type": "null"
    }, 
    "discountinuedResnCdCncptId": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/discountinuedResnCdCncptId", 
      "title": "The discountinuedresncdcncptid schema.", 
      "type": "null"
    }, 
    "dose": {
      "default": 500, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "500"
      ], 
      "id": "/properties/dose", 
      "title": "The dose schema.", 
      "type": "integer"
    }, 
    "doseFormCodeCncptId": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/doseFormCodeCncptId", 
      "title": "The doseformcodecncptid schema.", 
      "type": "null"
    }, 
    "doseUnitCodeCncptId": {
      "default": 493417, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "493417"
      ], 
      "id": "/properties/doseUnitCodeCncptId", 
      "title": "The doseunitcodecncptid schema.", 
      "type": "integer"
    }, 
    "drugDescription": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/drugDescription", 
      "title": "The drugdescription schema.", 
      "type": "null"
    }, 
    "drugProtocolId": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/drugProtocolId", 
      "title": "The drugprotocolid schema.", 
      "type": "null"
    }, 
    "duration": {
      "default": 7, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "7"
      ], 
      "id": "/properties/duration", 
      "title": "The duration schema.", 
      "type": "integer"
    }, 
    "durationUnitCodeCncptId": {
      "default": 7, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "7"
      ], 
      "id": "/properties/durationUnitCodeCncptId", 
      "title": "The durationunitcodecncptid schema.", 
      "type": "integer"
    }, 
    "effectiveDate": {
      "default": "08/21/2017", 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "08/21/2017"
      ], 
      "id": "/properties/effectiveDate", 
      "title": "The effectivedate schema.", 
      "type": "string"
    }, 
    "effectiveDateEstimatedInd": {
      "default": "N", 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "N"
      ], 
      "id": "/properties/effectiveDateEstimatedInd", 
      "title": "The effectivedateestimatedind schema.", 
      "type": "string"
    }, 
    "encounterId": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/encounterId", 
      "title": "The encounterid schema.", 
      "type": "null"
    }, 
    "frequency": {
      "default": "3X", 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "3X"
      ], 
      "id": "/properties/frequency", 
      "title": "The frequency schema.", 
      "type": "string"
    }, 
    "genericDrugName": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/genericDrugName", 
      "title": "The genericdrugname schema.", 
      "type": "null"
    }, 
    "investigationId": {
      "default": 81111, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "81111"
      ], 
      "id": "/properties/investigationId", 
      "title": "The investigationid schema.", 
      "type": "integer"
    }, 
    "isDeletedInd": {
      "default": "N", 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "N"
      ], 
      "id": "/properties/isDeletedInd", 
      "title": "The isdeletedind schema.", 
      "type": "string"
    }, 
    "lockSeqNum": {
      "default": 0, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "0"
      ], 
      "id": "/properties/lockSeqNum", 
      "title": "The lockseqnum schema.", 
      "type": "integer"
    }, 
    "modifiedBy": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/modifiedBy", 
      "title": "The modifiedby schema.", 
      "type": "null"
    }, 
    "modifiedOn": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/modifiedOn", 
      "title": "The modifiedon schema.", 
      "type": "null"
    }, 
    "nonhumanSubjectId": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/nonhumanSubjectId", 
      "title": "The nonhumansubjectid schema.", 
      "type": "null"
    }, 
    "orderDuration": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/orderDuration", 
      "title": "The orderduration schema.", 
      "type": "null"
    }, 
    "orderDurationUntCdCncptId": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/orderDurationUntCdCncptId", 
      "title": "The orderdurationuntcdcncptid schema.", 
      "type": "null"
    }, 
    "otherMedInd": {
      "default": "N", 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "N"
      ], 
      "id": "/properties/otherMedInd", 
      "title": "The othermedind schema.", 
      "type": "string"
    }, 
    "prescribedBy": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/prescribedBy", 
      "title": "The prescribedby schema.", 
      "type": "null"
    }, 
    "prescribedByProviderOther": {
      "default": "Other", 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "Other"
      ], 
      "id": "/properties/prescribedByProviderOther", 
      "title": "The prescribedbyproviderother schema.", 
      "type": "string"
    }, 
    "prescripReasonCodeCncptId": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/prescripReasonCodeCncptId", 
      "title": "The prescripreasoncodecncptid schema.", 
      "type": "null"
    }, 
    "prescriptionDate": {
      "default": "08/21/2017", 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "08/21/2017"
      ], 
      "id": "/properties/prescriptionDate", 
      "title": "The prescriptiondate schema.", 
      "type": "string"
    }, 
    "prescriptionId": {
      "default": 12299, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "12299"
      ], 
      "id": "/properties/prescriptionId", 
      "title": "The prescriptionid schema.", 
      "type": "integer"
    }, 
    "prescriptionReasonOther": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/prescriptionReasonOther", 
      "title": "The prescriptionreasonother schema.", 
      "type": "null"
    }, 
    "prevSubjectId": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/prevSubjectId", 
      "title": "The prevsubjectid schema.", 
      "type": "null"
    }, 
    "reasnDrgNtStppdCdCncptId": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/reasnDrgNtStppdCdCncptId", 
      "title": "The reasndrgntstppdcdcncptid schema.", 
      "type": "null"
    }, 
    "reasonDrugStoppdCdCncptId": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/reasonDrugStoppdCdCncptId", 
      "title": "The reasondrugstoppdcdcncptid schema.", 
      "type": "null"
    }, 
    "routeCodeCncptId": {
      "default": 1279134, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "1279134"
      ], 
      "id": "/properties/routeCodeCncptId", 
      "title": "The routecodecncptid schema.", 
      "type": "integer"
    }, 
    "specialDirection": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/specialDirection", 
      "title": "The specialdirection schema.", 
      "type": "null"
    }, 
    "startDate": {
      "default": "08/21/2017", 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "08/21/2017"
      ], 
      "id": "/properties/startDate", 
      "title": "The startdate schema.", 
      "type": "string"
    }, 
    "subjectId": {
      "default": 2468043, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "2468043"
      ], 
      "id": "/properties/subjectId", 
      "title": "The subjectid schema.", 
      "type": "integer"
    }, 
    "treatmentDurUnitCncptId": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/treatmentDurUnitCncptId", 
      "title": "The treatmentdurunitcncptid schema.", 
      "type": "null"
    }, 
    "treatmentDuration": {
      "default": null, 
      "description": "An explanation about the purpose of this instance.", 
      "examples": [
        "None"
      ], 
      "id": "/properties/treatmentDuration", 
      "title": "The treatmentduration schema.", 
      "type": "null"
    }
  }, 
  "type": "object"
}

=== dukai2016/test/testproject/src/test/resources/treatmentData.json
{
     "prescriptionId": 12299,
                "prescriptionDate": "08/21/2017",
                "prescripReasonCodeCncptId": null,
                "prescribedBy": null,
                "effectiveDate": "08/21/2017",
                "courseCompletedCodeCncptId": null,
                "frequency": "3X",
                "routeCodeCncptId": 1279134,
                "specialDirection": null,
                "durationUnitCodeCncptId": 7,
                "genericDrugName": null,
                "dose": 500,
                "doseUnitCodeCncptId": 493417,
                "startDate": "08/21/2017",
                "doseFormCodeCncptId": null,
                "drugDescription": null,
                "orderDurationUntCdCncptId": null,
                "isDeletedInd": "N",
                "lockSeqNum": 0,
                "modifiedBy": null,
                "modifiedOn": null,
                "createdBy": "ESTI_DEMO",
                "createdOn": "08/21/2017",
                "catalogueItemId": 112,
                "subjectId": 2468043,
                "actualEndDate": null,
                "discountinuedResnCdCncptId": null,
                "discontinuedDate": null,
                "discontinuedBy": null,
                "reasnDrgNtStppdCdCncptId": null,
                "nonhumanSubjectId": null,
                "discontinuedByProviderOther": null,
                "prescribedByProviderOther": "Other",
                "otherMedInd": "N",
                "prevSubjectId": null,
                "prescriptionReasonOther": null,
                "reasonDrugStoppdCdCncptId": null,
                "effectiveDateEstimatedInd": "N",
                "duration": 7,
                "orderDuration": null,
                "catalogueItemIdL2": 45,
                "treatmentDuration": null,
                "treatmentDurUnitCncptId": null,
                "investigationId": 81111,
                "encounterId": null,
                "drugProtocolId": null
}
